# Generated by Django 4.2.30 on 2026-06-18 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن')),
                ('notification_type', models.CharField(choices=[('ORDER_CREATED', 'ثبت سفارش'), ('ORDER_STATUS_CHANGED', 'تغییر وضعیت سفارش'), ('ADMIN_MESSAGE', 'پیام ادمین'), ('KYC_APPROVED', 'تأیید احراز هویت'), ('KYC_REJECTED', 'رد احراز هویت')], db_index=True, max_length=30, verbose_name='نوع اعلان')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_read_created_idx')],
            },
        ),
    ]
