# Generated by Django 4.2.30 on 2026-06-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'ثبت سفارش'), ('ORDER_STATUS_CHANGED', 'تغییر وضعیت سفارش'), ('ADMIN_MESSAGE', 'پیام ادمین'), ('KYC_APPROVED', 'تأیید احراز هویت'), ('KYC_REJECTED', 'رد احراز هویت'), ('KYC_NEEDS_CORRECTION', 'درخواست اصلاح احراز هویت'), ('PAYMENT_APPROVED', 'تأیید پرداخت'), ('PAYMENT_REJECTED', 'رد پرداخت')], db_index=True, max_length=30, verbose_name='نوع اعلان'),
        ),
    ]
